project:
  type: website
  output-dir: docs

website:
  title: JÃ³hanna K Birnir
  navbar:
    background: maroon
    foreground: white
    left:
      - text: "Home"
        href: index.qmd #href	Link to file contained with the project or external URL.
      - text: "Research"
        href: research.qmd
      - text: "Data"
        href: data.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Personal"
        href: personal.qmd

  comments:
    giscus:
      repo: jkbirnir/johannabirnir
      loading: lazy
      theme: dark 

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

